### ISSUE TITLE
dataelements.md tables not accessible

### ISSUE THREAD

**Issue by bsweger** [kaitlin/fedspendingtransparency#3]
According to yesterday's @nickbristow training re: accessibility, the tables on the Data Elements page (https://github.com/kaitlin/fedspendingtransparency/blob/gh-pages/dataelements.md) need some additional tags. I suppose the solution is to convert this info from markdown to HTML before we roll these changes into the production site.

http://18f.github.io/accessibility/tables/

**Comment by nickbristow** [comment]
This is true, they look like simple tables, so just add scope attributes to your headers.

**Comment by bsweger** [comment]
Fixed via 2128fa3edb5d7b2648df595be43f2437ccceadbc
